service: ${file(../service.yml)}

plugins:
  - serverless-s3-sync

provider:
  name: aws
  runtime: ruby2.7
  stage: live
  region: ${file(../region.yml)}

functions:
  hello:
    handler: handler.hello
    events:
    - http:
        path: hello
        method: get

custom:
  siteName: ${file(../s3-bucket-name.yml)}

  s3Sync:
    - bucketName: ${self:custom.siteName}
      localDir: static

resources:
  Outputs:
    Website:
      Value: http://${self:custom.siteName}.s3-website.${self:provider.region}.amazonaws.com/
  Resources:
    - ${file(../resource-s3-bucket.yml)}
    - ${file(../resource-s3-bucket-policy.yml)}
