service: serverless-workshop-part-1

provider:
  name: aws
  runtime: ruby2.5

  stage: dev
  region: eu-central-1

functions:
  hello:
    handler: handler.hello
    events:
    - http:
        path: hello
        method: get
