service: ${file(../service.yml)}

provider:
  name: aws
  runtime: ruby2.7
  stage: live
  region: ${file(../region.yml)}

functions:
  hello:
    handler: handler.hello
    events:
    - http:
        path: hello
        method: get
